# NoteVault Configuration Example
# Copy this file to config.toml and customize for your environment

[app]
name = "NoteVault"
version = "1.0.0"
environment = "development"  # development, staging, production
port = 3000
host = "localhost"
base_url = "http://localhost:3000"
timezone = "UTC"

[database]
# Use SQLite for development, PostgreSQL for production
type = "sqlite"
sqlite_path = "./server/database/notevault.db"
# postgresql_url = "postgresql://username:password@localhost:5432/notevault"

[redis]
enabled = true
url = "redis://localhost:6379"
database = 0

[security]
# IMPORTANT: Change these secrets in production!
jwt_secret = "your-super-secret-jwt-key-change-this-in-production"
session_secret = "your-session-secret-change-this-in-production"
csrf_secret = "your-csrf-secret-change-this-in-production"

[security.rate_limiting]
enabled = true
max_requests = 100

[oauth]
# Configure OAuth providers as needed

[oauth.google]
enabled = false
# client_id = "your-google-client-id"
# client_secret = "your-google-client-secret"

[oauth.github]
enabled = false
# client_id = "your-github-client-id"
# client_secret = "your-github-client-secret"

[email]
enabled = false
# Configure email service for production

[storage]
default_provider = "local"

[integrations]
# Enable integrations as needed

[integrations.slack]
enabled = false
# bot_token = "xoxb-your-slack-bot-token"

[integrations.discord]
enabled = false
# bot_token = "your-discord-bot-token"

[features]
registration_enabled = true
guest_access_enabled = true
collaboration_enabled = true

[ui]
default_theme = "light"
default_language = "en"