# NoteVault Configuration File
# This file contains all configuration options for the NoteVault platform
# Copy this file to config.toml and customize for your environment

[app]
name = "NoteVault"
version = "1.0.0"
environment = "development"  # development, staging, production
port = 3000
host = "localhost"
base_url = "http://localhost:3000"
timezone = "UTC"

[database]
# Primary database configuration
type = "sqlite"  # sqlite, postgresql
sqlite_path = "./server/database/notevault.db"
postgresql_url = "postgresql://username:password@localhost:5432/notevault"
pool_min = 2
pool_max = 10
ssl = false
migration_table = "migrations"
auto_migrate = true

[redis]
# Redis configuration for sessions and caching
enabled = true
url = "redis://localhost:6379"
password = ""
database = 0
key_prefix = "notevault:"
session_ttl = 86400  # 24 hours in seconds

[security]
# Security and authentication settings
jwt_secret = "your-super-secret-jwt-key-change-this-in-production"
jwt_expires_in = "7d"
bcrypt_rounds = 12
session_secret = "your-session-secret-change-this-in-production"
csrf_secret = "your-csrf-secret-change-this-in-production"
cookie_secure = false  # Set to true in production with HTTPS
cookie_same_site = "lax"

# Rate limiting configuration
[security.rate_limiting]
enabled = true
window_ms = 900000  # 15 minutes
max_requests = 100
auth_max_requests = 5
upload_max_requests = 10
skip_successful_requests = false

# Two-Factor Authentication
[security.totp]
enabled = true
issuer = "NoteVault"
window = 1
digits = 6
period = 30

[oauth]
# OAuth provider configurations

[oauth.google]
enabled = false
client_id = "your-google-client-id"
client_secret = "your-google-client-secret"
redirect_uri = "http://localhost:3000/auth/google/callback"

[oauth.github]
enabled = false
client_id = "your-github-client-id"
client_secret = "your-github-client-secret"
redirect_uri = "http://localhost:3000/auth/github/callback"

[oauth.discord]
enabled = false
client_id = "your-discord-client-id"
client_secret = "your-discord-client-secret"
redirect_uri = "http://localhost:3000/auth/discord/callback"

[email]
# Email service configuration
enabled = false
provider = "smtp"  # smtp, sendgrid, mailgun, ses
from_address = "noreply@notevault.com"
from_name = "NoteVault"

[email.smtp]
host = "smtp.gmail.com"
port = 587
secure = false  # true for 465, false for other ports
username = "your-email@gmail.com"
password = "your-app-password"

[email.sendgrid]
api_key = "your-sendgrid-api-key"

[email.mailgun]
api_key = "your-mailgun-api-key"
domain = "your-mailgun-domain"

[email.ses]
access_key_id = "your-aws-access-key"
secret_access_key = "your-aws-secret-key"
region = "us-east-1"

[storage]
# File storage configuration
default_provider = "local"  # local, s3, cloudinary

[storage.local]
upload_path = "./uploads"
max_file_size = 10485760  # 10MB in bytes
allowed_types = ["image/jpeg", "image/png", "image/gif", "application/pdf", "text/plain"]

[storage.s3]
enabled = false
bucket = "your-s3-bucket"
region = "us-east-1"
access_key_id = "your-aws-access-key"
secret_access_key = "your-aws-secret-key"
endpoint = ""  # Optional: for S3-compatible services

[storage.cloudinary]
enabled = false
cloud_name = "your-cloudinary-cloud-name"
api_key = "your-cloudinary-api-key"
api_secret = "your-cloudinary-api-secret"

[cdn]
# CDN configuration
enabled = false
provider = "cloudflare"  # cloudflare, aws, fastly, bunny

[cdn.cloudflare]
zone_id = "your-cloudflare-zone-id"
api_token = "your-cloudflare-api-token"
base_url = "https://cdn.yourdomain.com"

[cdn.aws]
distribution_id = "your-cloudfront-distribution-id"
access_key_id = "your-aws-access-key"
secret_access_key = "your-aws-secret-key"
region = "us-east-1"
base_url = "https://your-distribution.cloudfront.net"

[cdn.fastly]
service_id = "your-fastly-service-id"
api_token = "your-fastly-api-token"
base_url = "https://your-service.fastly.com"

[websocket]
# WebSocket configuration for real-time features
enabled = true
cors_origin = "*"
ping_timeout = 60000
ping_interval = 25000
max_connections = 1000

[monitoring]
# Monitoring and analytics configuration
enabled = true
provider = "prometheus"  # prometheus, datadog, newrelic

[monitoring.prometheus]
metrics_path = "/metrics"
default_labels = { service = "notevault", version = "1.0.0" }

[monitoring.sentry]
enabled = false
dsn = "your-sentry-dsn"
environment = "development"
release = "1.0.0"

[logging]
# Logging configuration
level = "info"  # error, warn, info, verbose, debug
format = "combined"  # combined, common, dev, short, tiny
file_enabled = false
file_path = "./logs/notevault.log"
file_max_size = "10m"
file_max_files = 5

[backup]
# Backup configuration
enabled = true
provider = "local"  # local, s3
schedule = "0 2 * * *"  # Daily at 2 AM (cron format)
retention_days = 30
compression = true

[backup.local]
path = "./backups"

[backup.s3]
bucket = "your-backup-bucket"
region = "us-east-1"
access_key_id = "your-aws-access-key"
secret_access_key = "your-aws-secret-key"

# Integration configurations
[integrations]

[integrations.slack]
enabled = false
bot_token = "xoxb-your-slack-bot-token"
signing_secret = "your-slack-signing-secret"
webhook_url = "your-slack-webhook-url"
default_channel = "#general"

[integrations.discord]
enabled = false
bot_token = "your-discord-bot-token"
webhook_url = "your-discord-webhook-url"
application_id = "your-discord-application-id"
public_key = "your-discord-public-key"

[integrations.calendar]
enabled = false

[integrations.calendar.google]
enabled = false
client_id = "your-google-calendar-client-id"
client_secret = "your-google-calendar-client-secret"
redirect_uri = "http://localhost:3000/api/calendar/callback/google"

[integrations.calendar.outlook]
enabled = false
client_id = "your-outlook-client-id"
client_secret = "your-outlook-client-secret"
redirect_uri = "http://localhost:3000/api/calendar/callback/outlook"

[integrations.cloud_sync]
enabled = false

[integrations.cloud_sync.google_drive]
enabled = false
client_id = "your-google-drive-client-id"
client_secret = "your-google-drive-client-secret"
redirect_uri = "http://localhost:3000/api/cloud-sync/callback/google"

[integrations.cloud_sync.dropbox]
enabled = false
client_id = "your-dropbox-app-key"
client_secret = "your-dropbox-app-secret"
redirect_uri = "http://localhost:3000/api/cloud-sync/callback/dropbox"

[integrations.git]
enabled = false

[integrations.git.github]
enabled = false
client_id = "your-github-app-client-id"
client_secret = "your-github-app-client-secret"
webhook_secret = "your-github-webhook-secret"

[integrations.git.gitlab]
enabled = false
client_id = "your-gitlab-app-client-id"
client_secret = "your-gitlab-app-client-secret"
base_url = "https://gitlab.com"  # or your GitLab instance URL

[integrations.webhooks]
enabled = true
max_retries = 3
retry_delays = [1000, 5000, 30000]  # milliseconds
timeout = 10000  # 10 seconds
signature_algorithm = "sha256"

[features]
# Feature flags
registration_enabled = true
email_verification_required = false
approval_required = false
guest_access_enabled = true
file_uploads_enabled = true
chat_enabled = true
canvas_notes_enabled = true
collaboration_enabled = true
themes_enabled = true
i18n_enabled = true
analytics_enabled = true
audit_logging_enabled = true
backup_enabled = true
webhooks_enabled = true

[ui]
# User interface configuration
default_theme = "light"  # light, dark, cyberpunk, forest, ocean, sunset
default_layout = "classic"  # classic, focus, widescreen, compact
default_language = "en"
items_per_page = 20
max_search_results = 100
enable_animations = true
enable_shortcuts = true

[performance]
# Performance tuning
cache_ttl = 3600  # 1 hour
compression_enabled = true
minify_assets = true
lazy_loading = true
image_optimization = true
database_query_timeout = 30000  # 30 seconds

[development]
# Development-only settings
hot_reload = true
debug_mode = false
mock_integrations = false
seed_database = true
cors_enabled = true
cors_origin = "*"

[production]
# Production-specific settings
serve_static = false  # Use nginx/CDN in production
trust_proxy = true
secure_cookies = true
hsts_enabled = true
csp_enabled = true
helmet_enabled = true