version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: notevault-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/database/notevault.db
      - JWT_SECRET=docker-jwt-secret-change-in-production
      - CORS_ORIGIN=http://localhost:3000,http://frontend:3000
    volumes:
      - backend_data:/app/database
      - uploads_data:/app/uploads
    networks:
      - notevault-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: notevault-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - notevault-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: notevault-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - notevault-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
  uploads_data:
    driver: local

networks:
  notevault-network:
    driver: bridge